#!/bin/bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_ROOT="$(dirname "$ROOT_DIR")"

# Which docker image to use
DOCKER_IMG="rust-dev"

if [ -z "$1" ]; then
    # No argument, use defualt tag
    DOCKER_IMG_TAG="latest"
else
    DOCKER_IMG_TAG="$1"
fi

SRC_DIR="$PROJECT_ROOT"
DST_DIR="/home/user/$(basename "$PROJECT_ROOT")"

docker run -it -d --rm -v $SRC_DIR:$DST_DIR --name rust_docker $DOCKER_IMG:$DOCKER_IMG_TAG
